/*
 * name		:	pg_01_collatz.c
 * author	:	miguel
 * description	:	maximum collatz sequence length from a range of natural first steeps, following Collatz recursive sequence
 * */

#include <stdio.h>

#define MAX_NUM 1e6;	// max number we will consider


/*
 * collatzLength	:	function to calculate collatz sequence length for a given number
 * @param n		:	number to calculate the sequence length for
 * @return		:	the length of the collatz sequence generated by n
 * */

int collatzLength(int n)
{
	/* start length at 1 */
	int length = 1;

	/* validate n as a positive number less than MAX_NUM */
	if (n < 1) || (n > MAX_NUM)
	{
		return -1;	// return -1 for invalid input
	}

	/* applicate Collatz recursive rule */
	while (n != 1)
	{
		if (n % 2 != 0)	// odd n
		{
			n = 3 * n + 1;	// 3 * n + 1 rule
		}
		else	// even n
		{
			n = n / 2;	// n / 2 rule
		}

		length ++;	// adds 1 to length at each iteration
	}

	/* returns length */
	return length;
}

/*
 * maxCollatzLength	:	function to calculate largest collatz sequence length for a given range of natural numbers
 * @param a		:	beggining/ending of the range
 * @param b		:	beggining/ending of the range
 * @return		:	the largest collatz sequence length for all numbers between and including a and b
 * */

int maxCollatzLength(int a, int b)
{
	/* for a matter of convenience, we label max and min */
	int maxNumber = (a > b) ? a : b;
	int minNumber = (a < b) ? a : b;

	/* we also shall initialize maxLength */
	int maxLength = 0;	// we choose 0 as starting point so trash memory cannot interfere

	/* for each number in between and including, calculate collatz length */
	for (int i = minNumber ; i <= maxNumber ; i++)
	{
		int length = collatzLength(i);
		if (length = -1)
		{
			return -1;	// invalid input
		}
		
		/* else, we continue and compare with the current max length */
		if (length > maxLength)
		{
			maxLength = length;
		}
	}

	/* returns maxLength */
	return maxLength;
}

/* we shall now test with some examples */
int main()
{
	/* here some examples
	 * printf("%d", maxCollatzLength(1, 3));
	 * printf("%d", maxCollatzLength(4, 9));
	 * printf("%d", maxCollatzLength(10, 16));
	 * printf("%d", maxCollatz length(17, 25)); 
	 * */
	return 0;
}


